version: '3'

# run  sudo rm -rf ./data/postgres/ to make changes on db entrypoint
# if the previous does not work run docker-compose rm -fv db to remove the db image
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: fullstack #changes here require changes on .env file for Node.js
      POSTGRES_PASSWORD: fullstack
    volumes: # volumes copy directories from host to docker
#      - ./init_sql:/docker-entrypoint-initdb.d/ #This file generetes all tables for user $POSTGRES_USER
      - ./init-user-db:/docker-entrypoint-initdb.d/ #This allows creating other users ans tables
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432" # specify port forewarding
  app:
    env_file:
      - env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/
    working_dir: /usr/src/
#    command: npm run start
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start' #test if db is up before running node
    links:
      - db
    ports:
      - "4000:4000" # specify port forewarding
    depends_on:
      - db