version: '3'

#run  sudo rm -rf ./data/postgres/ to make changes on db entrypoint

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: intelbras
      POSTGRES_PASSWORD: intelbras
    volumes:
#      - ./init-user-db:/docker-entrypoint-initdb.d/
      - ./init_sql:/docker-entrypoint-initdb.d/
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432" # specify port forewarding
  app:
    env_file:
      - env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/
    working_dir: /usr/src/
    command: npm run start
    links:
      - db
    ports:
      - "4000:4000" # specify port forewarding
    depends_on:
      - db