version: '3'

services:
  db:
    image: postgres
  app:
    env_file:
      - env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
#    ports:
#      - "4000:4000"
    depends_on:
      - db